### PR TITLE
loginpwd

### PR DESCRIPTION
**Pull request by Patrick0906**
登入頁 PWD
layout 的 application.html.erb
<head>裡加上
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=1">

### CODE REVIEW

**Comment by Patrick0906** [comment]
meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=1"

**Comment by River-Ye** [comment]
LGTM

**Comment by joanliao0525** [comment]
Lgtm

**Comment by axelchen** [comment]
LGTM

**Pull request merged**
